### ISSUE TITLE
error reading book: 1:44 Unsupported encoding: windows-1251

### ISSUE THREAD

**Issue by aellwein** [r-glazkov/fb2#1]
Попробовал каталогизировать коллекцию lib.rus.ec при помощи пакета fb2, всплывает много ошибок вроде "error reading book: 1:44 Unsupported encoding: windows-1251". Как я понимаю, стандартная кодировка в XML utf-8, но очень многие книги используют windows-1251 (русская кодировка на Виндовс). 

@r-glazkov Вам знакома эта ошибка? Что можно сделать?

**Comment by r-glazkov** [comment]
Здравствуйте! К сожалению, библиотека для XML не поддерживает windows-1251: https://github.com/netvl/xml-rs
Она поддерживает только UTF-16, UTF-8, ISO-8859-1, и ASCII.

На данный момент, можно выкрутиться таким способом:

```rust
use encoding_rs::Encoding;
use encoding_rs_io::DecodeReaderBytesBuilder;
use fb2::FictionBook;

fn parse_fb2(bytes: &[u8]) -> Result<FictionBook, fb2::Error> {
    let mut book = fb2::parse(bytes.as_ref());
    let encoding = get_encoding_from_error(&book);
    if let Some(encoding) = encoding {
        let mut decoder = DecodeReaderBytesBuilder::new()
            .encoding(Encoding::for_label(encoding.as_bytes()))
            .build(bytes.as_ref());
        let mut decoded = String::new();
       // TODO: handle IO error
        decoder.read_to_string(&mut decoded).unwrap();
        book = fb2::parse(
            decoded
                .replacen(&encoding, encoding_rs::UTF_8.name(), 1)
                .as_bytes(),
        );
    }
    book
}

fn get_encoding_from_error(book: &Result<FictionBook, fb2::Error>) -> Option<String> {
    match book {
        Ok(_) => None,
        Err(e) => match e {
            fb2::Error::Xml(e) => {
                if let xml::reader::ErrorKind::Syntax(msg) = e.kind() {
                    if let Some(encoding) = msg.strip_prefix("Unsupported encoding: ") {
                        Some(encoding.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                }
            }
            _ => None,
        },
    }
}
```

Как будет время, попробую заменить библиотеку на [quick-xml](https://github.com/tafia/quick-xml). Эта библиотека поддерживает больше кодировок.

**Comment by aellwein** [comment]
Спасибо, я попробую.

**Comment by DmitrySorda** [comment]
У меня не работает. 
Ошибка следующая: Error parsing XML: Custom("missing field `description`")
Файл взят отсюда https://www.nalog.gov.ru/html/sites/www.new.nalog.ru/xsd/ON_NSCHFDOPPOK_1_997_02_05_01_02.xsd
`use std::fs::File;
 use std::io::BufReader;
use fb2::FictionBook;

fn main() {
    // Note: Result type added to handle the potential error from File::open
    let file_result = File::open("/Users/Downloads/ON_NSCHFDOPPOK_1_997_02_05_01_02.xsd.xml");

match file_result {
        Ok(file) => {
            let reader = BufReader::new(file);

            match quick_xml::de::from_reader::<BufReader<File>, FictionBook>(reader) {
                Ok(book) => {
                    println!("{:#?}", book);
                }
                Err(error) => {
                    // Handle the parsing error
                    println!("Error parsing XML: {:?}", error);
                }
            }
        }
        Err(error) => {
            // Handle the file open error
            println!("Error opening file: {:?}", error);
        }
    }
}`
